language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson libgee-0.8-dev valac git"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/ && git clone https://github.com/peteruithoven/vala-lint.git --branch 3-phases &&  cd vala-lint && meson build --prefix=/usr && cd build && ninja && ./io.elementary.vala-lint -d /tmp/build-dir/src"

script:
 - echo BUILDS PASSED
